/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.6
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.liveproject.openbankinapp.integration.openbanking.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Rate type for Fee/Charge (where it is charged in terms of a rate rather than an amount)
 */
public enum OBInterestRateType1Code1 {
  INBB("INBB"),
  INFR("INFR"),
  INGR("INGR"),
  INLR("INLR"),
  INNE("INNE"),
  INOT("INOT");

  private String value;

  OBInterestRateType1Code1(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static OBInterestRateType1Code1 fromValue(String text) {
    for (OBInterestRateType1Code1 b : OBInterestRateType1Code1.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
